name: Android CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

    workflow_dispatch:

jobs:
    build:
        name: Lint, Test and Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Cache Gradle packages
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Create google-services.json
              run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/google-services.json

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Run Spotless Check
              run: ./gradlew spotlessCheck

            - name: Run unit tests and create coverage report
              run: ./gradlew testDebugUnitTest createDebugCoverageReport

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: ipirangad3v/my-diary-android-app

            - name: Build Release App Bundle
              run: ./gradlew bundleRelease

            - name: Upload App Bundle Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: my-diary-app-bundle
                  path: app/build/outputs/bundle/release/app-release.aab

    deploy:
        name: Deploy to Play Store
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download App Bundle
              uses: actions/download-artifact@v4
              with:
                  name: my-diary-app-bundle

            - name: Sign App Bundle
              id: sign
              uses: r0adkll/sign-android-release@v1
              with:
                  releaseDirectory: .
                  signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
                  alias: ${{ secrets.SIGNING_KEY_ALIAS }}
                  keyStorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
                  keyPassword: ${{ secrets.SIGNING_KEY_ALIAS_PASSWORD }}

            - name: Upload to Google Play
              uses: r0adkll/upload-google-play@v1
              with:
                  serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
                  packageName: digital.tonima.mydiary
                  releaseFiles: ${{ steps.sign.outputs.signedReleaseFile }}
                  track: internal
                  whatsNewDirectory: whatsnew/
